name: CircleCI Port

on:
  workflow_dispatch:
  push:

env:
  # TODO: extend duration once workflow is fully migrated
  result_retention_days: 2

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, nscloud] # TODO: only run nscloud
    runs-on: ${{ matrix.os }}
    steps:
      # install
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup cross-invocation caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('setup.cfg') }}
      - name: Setup environment
        run: |
          make install

      # preflight
      - name: Linting
        run: |
          make lint

      # unit-tests
      - name: Unit tests
        env:
          TEST_PATH: tests/unit
          PYTEST_ARGS: --junitxml=unit-tests.xml -o junit_suite_name=unit-tests
          COVERAGE_ARGS: -p
        run: |
          make test-coverage
      # Sadly actions/test-reporter does not support Python yet.
      # Maybe there is a better alternative to `store_test_results`.
      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: results-${{ matrix.os }}
          path: |
            unit-tests.xml
            .coverage.*
          retention-days: ${{ env.result_retention_days }}

  itest-lambda-legacy-local:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, nscloud] # TODO: only run nscloud
    runs-on: ${{ matrix.os }}
    steps:
      # install
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup cross-invocation caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('setup.cfg') }}
      - name: Setup environment
        run: |
          make install

      # preflight
      - name: Linting
        run: |
          make lint

      # itest-lambda-legacy-local
      - name: Test 'local' Lambda executor
        env:
          LAMBDA_EXECUTOR: local
          PROVIDER_OVERRIDE_LAMBDA: legacy
          TEST_PATH: tests/integration/awslambda/ tests/integration/test_integration.py tests/integration/apigateway/test_apigateway_basic.py tests/integration/cloudformation/resources/test_lambda.py
          PYTEST_ARGS: --reruns 2 --junitxml=lambda-docker.xml -o junit_suite_name='legacy-lambda-local'
          COVERAGE_ARGS: -p
        run: |
          make test-coverage
      # Sadly actions/test-reporter does not support Python yet.
      # Maybe there is a better alternative to `store_test_results`.
      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: results-${{ runner.os }}
          path: |
            lambda-docker.xml
            .coverage.*
          retention-days: ${{ env.result_retention_days }}

  itest-sfn-v2-provider:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, nscloud] # TODO: only run nscloud
    runs-on: ${{ matrix.os }}
    steps:
      # install
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup cross-invocation caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('setup.cfg') }}
      - name: Setup environment
        run: |
          make install

      # preflight
      - name: Linting
        run: |
          make lint

      # itest-sfn-v2-provider
      - name: Test SFN V2 provider
        env:
          PROVIDER_OVERRIDE_STEPFUNCTIONS: v2
          TEST_PATH: tests/integration/stepfunctions/v2/
          PYTEST_ARGS: --reruns 3 --junitxml=sfn_v2.xml -o junit_suite_name='sfn_v2'
          COVERAGE_ARGS: -p
        run: |
          make test-coverage
      # Sadly actions/test-reporter does not support Python yet.
      # Maybe there is a better alternative to `store_test_results`.
      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: results-${{ runner.os }}
          path: |
            sfn_v2.xml
            .coverage.*
          retention-days: ${{ env.result_retention_days }}

  docker-build:
    strategy:
      matrix:
        platform: [amd64, arm64]
    runs-on: nscloud
    steps:
      # install
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup cross-invocation caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('setup.cfg') }}
      - name: Setup environment
        run: |
          make install

      # preflight
      - name: Linting
        run: |
          make lint

      # docker-build
      - name: Build community docker image
        run: |
          make docker-build
      - name: Save docker image
        run: |
          mkdir target
          PLATFORM="${{ matrix.platform }}" make docker-save-image
      - name: Load docker image
        run: |
          docker load -i target/localstack-docker-image-${{ matrix.platform }}.tar
      # TODO
